services:
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  piston:
    image: ghcr.io/engineer-man/piston
    ports:
      - "2000:2000"
    privileged: true
    tmpfs:
      - /piston/jobs:exec,uid=1000,gid=1000

  leetcode-api:
    build:
      context: .
      dockerfile: leetcode-api.Dockerfile
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - mongodb
      - piston
      - leetcode-api
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file: .env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongo_data:
